<template>
  <div>
    <h1>4. 検索・フィルタリング</h1>
    
    <h2>検索バー（トークン型検索）</h2>
    <p>ビューア上部に配置された検索バーにテキストを入力すると、条件のサジェストが表示され、トークンとして条件を追加できます。</p>
    
    <table>
      <thead>
        <tr>
          <th>種類</th>
          <th>入力例</th>
          <th>説明</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><strong>タグ検索</strong></td>
          <td>タグ名を入力</td>
          <td>タグ名、読み仮名(Ruby)、ローマ字、エイリアスで検索</td>
        </tr>
        <tr>
          <td><strong>フォルダ検索</strong></td>
          <td>フォルダパスを入力</td>
          <td>特定フォルダ内のファイルに絞り込み</td>
        </tr>
        <tr>
          <td><strong>プロパティ検索</strong></td>
          <td><code>prop.</code> で始まる入力</td>
          <td>専用ダイアログでプロパティ比較条件を設定</td>
        </tr>
        <tr>
          <td><strong>アルバム検索</strong></td>
          <td>アルバム名を入力</td>
          <td>特定アルバム内のファイルに絞り込み</td>
        </tr>
        <tr>
          <td><strong>アドレス検索</strong></td>
          <td>住所・地名を入力</td>
          <td>位置情報に基づく検索</td>
        </tr>
        <tr>
          <td><strong>ワード検索</strong></td>
          <td>任意テキスト</td>
          <td>ファイルパスに対するテキスト検索</td>
        </tr>
      </tbody>
    </table>

    <h3>プロパティ検索 (`prop.`)</h3>
    <p>詳細な条件で絞り込むための機能です。利用可能な演算子はプロパティの型によって異なります（例: <code>prop.Width >= 1920</code>, <code>prop.Rate > 3</code>）。</p>
    <ul>
      <li><strong>数値比較</strong> (<code>></code>, <code>>=</code>, <code>=</code>, <code><=</code>, <code><</code>): Rate, Width, Height, UsageCount, FileSize</li>
      <li><strong>日付比較</strong> (<code>></code>, <code>>=</code>, <code>=</code>, <code><=</code>, <code><</code>): CreationTime, ModifiedTime, LastAccessTime, RegisteredTime</li>
      <li><strong>一致比較</strong> (<code>=</code>): MediaType, IsExists, IsInvalid, IsAutoGeneratedThumbnail, IsUnderFolderGroup</li>
      <li><strong>文字列比較</strong> (<code>=</code>, <code>contains</code>): Description, DirectoryPath, FilePath</li>
    </ul>

    <h2>フィルタ条件</h2>
    <p>フィルタはプリセットとして保存・管理可能です。以下のフィルタを組み合わせて高度な絞り込みを行えます：</p>
    <ul>
      <li>タグフィルタ (特定タグの有無)</li>
      <li>ファイルパスフィルタ</li>
      <li>解像度フィルタ (幅・高さの範囲)</li>
      <li>評価フィルタ (レート値)</li>
      <li>メディアタイプフィルタ (画像/動画/PDF/アーカイブ等)</li>
      <li>位置情報フィルタ</li>
      <li>存在フィルタ (ファイルが実在するか)</li>
    </ul>
    <p>作成したフィルタは「フィルタマネージャー」ウィンドウで管理・編集できます。</p>

    <h2>ソート機能</h2>
    <p>ソート条件も複数組み合わせて設定でき、昇順/降順の切り替えが可能です。ソートマネージャーでプリセットとして管理できます。</p>
    <p>利用可能なソートキー: FilePath, CreationTime, ModifiedTime, LastAccessTime, RegisteredTime, FileSize, Rate, Location, Resolution, UsageCount</p>
  </div>
</template>
